---
# Copyright 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Deploy Sensu server cluster
  hosts: sensu
  gather_facts: true
  become: true
  become_user: root
  environment: "{{ deployment_environment_variables | default({}) }}"
  pre_tasks:
    - include_tasks: "/opt/openstack-ansible/playbooks/common-tasks/os-{{ container_tech | default('lxc') }}-container-setup.yml"
      when:
        - "inventory_hostname in groups['all_containers']"
    - include_tasks: /opt/openstack-ansible/playbooks/common-tasks/os-log-dir-setup.yml
      vars:
        log_dirs:
          - src: "/openstack/log/{{ inventory_hostname }}-sensu"
            dest: "{{ sensu_logs_dir }}"
    - include_tasks: /opt/openstack-ansible/playbooks/common-tasks/package-cache-proxy.yml
  roles:
    - role: sensu
      sensu_master: true
      sensu_include_dashboard: true
      rabbitmq_server: false
      rabbitmq_enable_ssl: "{{ sensu_rabbitmq_enable_ssl }}"
      rabbitmq_host: "{{ sensu_rabbitmq_host }}"
      rabbitmq_port: "{{ sensu_rabbitmq_port }}"
      rabbitmq_sensu_user_name: "{{ sensu_rabbitmq_user_name }}"
      rabbitmq_sensu_password: "{{ sensu_rabbitmq_user_password }}"
      rabbitmq_sensu_vhost: "{{ sensu_rabbitmq_vhost }}"
      redis_server: false
      # redis_host not used anymore (redis_sentinels used instead)
      # redis_host: "{{ sensu_redis_host }}"
      when:
        - "'sensu' in group_names"
    - role: rsyslog_client
      rsyslog_client_log_rotate_file: sensu_log_rotate
      rsyslog_client_log_dir: "{{ sensu_logs_dir }}"
      rsyslog_client_config_name: "99-sensu-rsyslog-client.conf"
      tags: [sensu-rsyslog]
- name: Deploy Sensu Client
  hosts: "all:!sensu"
  gather_facts: true
  become: true
  become_user: root
  roles:
    - role: sensu
      sensu_master: false
      sensu_include_dashboard: false
      rabbitmq_server: false
      rabbitmq_enable_ssl: "{{ sensu_rabbitmq_enable_ssl }}"
      rabbitmq_host: "{{ sensu_rabbitmq_host }}"
      rabbitmq_port: "{{ sensu_rabbitmq_port }}"
      rabbitmq_sensu_user_name: "{{ sensu_rabbitmq_user_name }}"
      rabbitmq_sensu_password: "{{ sensu_rabbitmq_user_password }}"
      rabbitmq_sensu_vhost: "{{ sensu_rabbitmq_vhost }}"
      redis_server: false
      # redis_host not used anymore (redis_sentinels used instead)
      # redis_host: "{{ sensu_redis_host }}"
    - role: rsyslog_client
      rsyslog_client_log_rotate_file: sensu_log_rotate
      rsyslog_client_log_dir: "{{ sensu_logs_dir }}"
      rsyslog_client_config_name: "99-sensu-rsyslog-client.conf"
      tags: [sensu-rsyslog]
