---
# Copyright 2016, Rackspace US, Inc.
# Copyright 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- name: Deploy Influxdb Relay
  hosts: "influxdb_relay"
  gather_facts: true
  user: root
  environment: "{{ onpc_environment_variables | default({}) }}"
  tasks:
    - include: /opt/openstack-ansible/playbooks/common-tasks/haproxy-endpoint-manage.yml
      vars:
        haproxy_backend: influxdb_relay-back
        haproxy_state: disabled
      when:
        - "'influxdb_relay' in group_names"
        - "groups['influxdb_relay'] | length > 1"
      tags: [influxdb-relay_disable_haproxy]
    - name: Check init system
      command: cat /proc/1/comm
      changed_when: false
      register: _init_name
      tags: [influxdb-relay-init]
    - name: Set the name of init system
      set_fact:
        init_name: "{{ _init_name.stdout }}"
      tags: [influxdb-relay_init]
    - name: Install dependencies 
      package:
        name: "{{ item }}" 
        state: "latest"
      with_items:
        - git
        - wget
      tags: [influxdb-relay_dependencies]
    - name: Install GOLang
      script: ../files/influxdb_relay/deploy_go.sh
      changed_when: false
      tags: [influxdb-relay_depedencencies]
    - name: Download and install influx-relay
      script: ../files/influxdb_relay/deploy_influxdbrelay.sh
      changed_when: false
      tags: [influxdb-relay_install]
    - name: Drop influx relay toml file
      template:
        src: ../templates/influxdb/relay.toml.j2
        dest: /opt/influxdb-relay/relay.toml
      tags: [influxdb-relay_install]
    - name: Drop Influx Relay upstart
      template:
        src: ../templates/influxdb/influxdbrelay.conf.j2
        dest: /etc/init/influxdbrelay.conf
      when: init_name == "init"
      tags: [influxdb-relay_install]
    - name: Drop Influx Relay service file
      template:
        src: ../templates/influxdb/influxdbrelay.service.j2
        dest: /etc/systemd/system/influxdbrelay.service
      when:  init_name == "systemd"
      tags: [influxdb-relay_install]
    - name: Enable and restart influxdb
      service:
        name: "influxdbrelay"
        state: restarted
    - include: /opt/openstack-ansible/playbooks/common-tasks/haproxy-endpoint-manage.yml
      vars:
        haproxy_backend: influxdb_relay-back
        haproxy_state: enabled
      when:
        - "'influxdb_relay' in group_names"
        - "groups['influxdb_relay'] | length > 1"
      tags: [influxdb-relay_enable_haproxy]

  vars_files:
    - ../vars/main.yml
    - ../vars/influxdb.yml
